{{- if include "isGcpOcpNewRelic" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
stringData:
  NEW_RELIC_LICENSE_KEY: {{ required "global.newrelic.licenseKey is required" .Values.global.newrelic.licenseKey | quote }}
{{ if .Values.global.newrelic.proxy }}
{{ if .Values.global.newrelic.proxy.usernameSecretKey }}
  NEW_RELIC_PROXY_USER: {{ .Values.global.newrelic.proxy.usernameSecretKey | quote }}
{{ end }}
{{ if .Values.global.newrelic.proxy.passwordSecretKey }}
  NEW_RELIC_PROXY_PASSWORD: {{ .Values.global.newrelic.proxy.passwordSecretKey | quote }}
{{ end }}
{{ end }}

{{- end -}}
