{{- if .Values.global.schema.upgrade.job.enabled }}
{{- if .Values.global.rationalizationdb.schema.autoManage.enabled }}
{{- if include "beginPreHookConfigAsset" . }}
{{ include "rationalizationdb-secret-template" . }}
{{ include "endPreHookConfigAsset" . }}
{{- end }}
{{- end }}
{{- end }}
