{{- if .Values.global.rationalization }}
{{- if .Values.global.rationalization.enabled }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-rationalization-api-service
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ if .Values.metrics }}  
    prometheus.io/scrape: "true"
    #prometheus.io/port: ""
    #prometheus.io/path: "/metrics"
{{ end }}
{{ include "getServiceAnnotations" . | indent 4 }}
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "service") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "service") | nindent 4 }}
spec:
  type: {{ include "getServiceType" . }}
  selector:
    app: {{.Release.Name}}-rationalization-api
{{ include "getExtraPodMatchLabels" (dict "dot" .) | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }} 
    targetPort: {{ .Values.api.targetPort }} 
    name: http
    {{ include "getNodePortFix" . | indent 4 | trim }}

{{- end }}
{{- end }}