{{- if .Values.global.orchestration.enabled }}
{{- if .Values.azure.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-orcazure-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
data:
{{- if include "isGcpEnabled" . }}
  azure-accesskey: {{ .Values.azure.accesskeySecretKey | b64enc | quote }}
{{- else }}
  azure-accesskey: {{ .Values.azure.accesskey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
