{{- if .Values.global.schema.upgrade.job.enabled }}
{{- if .Values.global.orcdb.schema.autoManage.enabled }}
{{- if include "beginPreHookConfigAsset" . }}
{{ include "orcdb-secret-template" . }}
{{ include "endPreHookConfigAsset" . }}
{{- end }}
{{- end }}
{{- end }}
