{{- if .Values.global.orchestration.enabled }}
{{- if .Values.sqs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-orcsqs-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
data:
{{- if include "isGcpEnabled" . }}
  sqs-keyid: {{ .Values.sqs.keyidSecretKey | b64enc | quote }}
  sqs-secretkey: {{ .Values.sqs.secretkeySecretKey | b64enc | quote }}
{{- else }}
  sqs-keyid: {{ .Values.sqs.keyid | b64enc | quote }}
  sqs-secretkey: {{ .Values.sqs.secretkey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
