{{- if and (include "needRabbitSecret" .) .Values.global.rabbitmq.tls.enabled .Values.global.rabbitmq.tls.useClientCertificate }}

{{- if .Values.global.rabbitmq.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-certs
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
data:
{{- if include "isGcpEnabled" . }}
  rabbitmq-cert: {{ required "global.rabbitmq.tls.certSecretKey is required" .Values.global.rabbitmq.tls.certSecretKey | b64enc  | indent 4 }}
  rabbitmq-key: {{ required "global.rabbitmq.tls.keySecretKey is required" .Values.global.rabbitmq.tls.keySecretKey | b64enc  | indent 4 }}
{{- else }}
  rabbitmq-cert: {{ required "global.rabbitmq.tls.cert is required" .Values.global.rabbitmq.tls.cert | b64enc  | indent 4 }}
  rabbitmq-key: {{ required "global.rabbitmq.tls.key is required" .Values.global.rabbitmq.tls.key | b64enc  | indent 4 }}
{{- end }}
{{- end }}
{{- end }}