{{- if .Values.global.schema.upgrade.job.enabled }}
{{- if .Values.global.dasdb.schema.autoManage.enabled }}
{{- if include "beginPreHookConfigAsset" . }}
{{ include "dasdb-secret-template" . }}
{{ include "endPreHookConfigAsset" . }}
{{- end }}
{{- end }}
{{- end }}
