{{- if .Values.global.design.enabled }}
{{- if include "dig" (list "gcp" "ai" "enabled" false .Values) }}
{{- if include "needGcpAiSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcp-ai-credentials-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
data:
{{- if include "isGcpEnabled" . }}
  gcp-credentials: {{ required "global.design.gcp.ai.credentialsSecretKey is required" .Values.global.design.gcp.ai.credentialsSecretKey | b64enc }}
{{- else }}
  gcp-credentials: {{ required "design.gcp.ai.credentials is required" .Values.gcp.ai.credentials | b64enc }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
