{{- if .Values.global.design.enabled }}
{{- if .Values.solr }}
{{- if .Values.solr.zkHosts }}
{{- if include "needSolrSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-solr-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: Opaque
data:
{{- if include "isGcpEnabled" . }}
  solr-username: {{ .Values.global.solr.usernameSecretKey | b64enc | quote }}
  solr-password: {{ .Values.global.solr.passwordSecretKey | b64enc | quote }}
{{- else }}
  solr-username: {{ .Values.solr.username | b64enc | quote }}
  solr-password: {{ .Values.solr.password | b64enc | quote }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
