# Umbrella chart's parent values will override subchart's values 
# Since the sub chart is considered standalone , it cannot access parent chart values
enabled: false
deployment: 
  containerPort: 8081
#  # optionally specify deployment and container names.
#  container:
#    name:
#  name:
svc: 
  port: 8081
  targetPort: 8081

debugger: false
allowedOrigins:
contentSecurityPolicy:

# Configures the strategy Deployments use to replace old Pods with new ones. Can 
# be set to RollingUpdate or Recreate. 
# 
# For more information see:
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
updateStrategy: RollingUpdate

# Optional values that can be set when using a RollingUpdate strategy for Deployments.
# Can be an absolute number or a percentage of desired Pods.
#
# Note: maxUnavailable and maxSurge cannot both be set to 0
#
# For more information see:
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge
# rollingUpdate:
#   maxUnavailable: 25%
#   maxSurge: 25%

versions:
  jdkVersion: "17.0.13"
  springBootVersion: "3.3.6"

replicaCount: 1
metrics: false

version: latest

# Optional custom settings for heap management.
# For example:
# "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:G1PeriodicGCInterval=10000 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:MaxRAMPercentage=80 -Xlog:gc=info"
heapFlags:

# Helm recommends not specifying default resources and to leave this as a 
# conscious choice for the user.
resources:
  migrator: {}
    # requests:
    #   cpu: ""
    #   memory: ""
    # limits:
    #   cpu: ""
    #   memory: ""
  schema: {}
    # requests:
    #   cpu: ""
    #   memory: ""
    # limits:
    #   cpu: ""
    #   memory: ""

livenessProbe:
  default:
    failureThreshold: 5
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 2

readinessProbe:
  default:
    failureThreshold: 2
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 2

db:
  schema:
    prefix: ""

    ## Should the design service be responsible for managing the database schema?
    autoManage:
      enabled: true
      username: 
      password: 

  ## Connection information to the design database
  externalDb:
    # The type of database.  Possible values: SQLSERVER | ORACLE | POSTGRES
    dbType: POSTGRES
    username: 
    password: 
    url: jdbc:postgresql://localhost:5432/exstream
    #url: "jdbc:sqlserver://localhost:1433;databaseName=exstream"
    #url: "jdbc:oracle:thin:@//localhost:1521/XE"
    ## System tenant schema
    schema:

    # usernameSuffix will be concatenated to the end of all usernames. For example Azure Postgres 
    # needs @hostname applied to the end of the username and in this case set usernameSuffix to @hostname.
    usernameSuffix: null
