{{- if and (or .Values.global.ondemand.enabled .Values.global.batch.enabled) .Values.global.dasdb.schema.autoManage.enabled -}}

{{- $docgenDockerImage:= include "getEngineUploadDocgenDockerImage" . -}}
{{- $containerName := "engine-installer" -}}
{{- $podName := "uploadJob" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-upload-included-engine-job{{- include "getHookJobNameSuffix" . }}
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
    {{ include "postInstallHookCustomAnnotations" (dict "dot" . "hook" "post-install, post-rollback, post-upgrade" "hookWeight" "0") | nindent 4 }}
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "job") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "job") | nindent 4 }}
{{- if .Values.global.azure.keyVault.enabled }}
    azure.workload.identity/use: 'true'
{{- end }}
spec:
{{ include "preInstallUpgradeSpecs" . | indent 2 }}
  template:
    metadata:
{{- if .Values.global.azure.keyVault.enabled }}
      namespace: {{ include "getExstreamReleaseNamespace" . }}
{{- end }}
      annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "pod") | nindent 8 }}
      labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "pod") | nindent 8 }}
{{- if .Values.global.azure.keyVault.enabled }}
        azure.workload.identity/use: 'true'
{{- end }}
    spec:
      {{ include "getNodeSelector" .Values | nindent 6 }}
      {{ include "getServiceAccount" .Values | nindent 6 }}
      {{ include "imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- include "sharedStorageRunAsIds" . | nindent 8 }}
      restartPolicy: Never
      containers:
      - name: {{ $containerName }}
        image: {{ $docgenDockerImage }}
        {{- include "imagePullPolicy" . | nindent 8 }}
        securityContext:
          {{- include "getReadOnlyRootFilesystemProperty" . | nindent 10 }}
          {{- include "getDefaultSecurityContextProperties" . | nindent 10 }}

        resources:
          {{ .Values.resources.uploadJob | toYaml | indent 10 | trim }}
        command: ["/home/exstream/src/scripts/common/init/start.sh", "/home/exstream/installEngine.sh"]
        volumeMounts:
          {{- if eq .Values.global.storage.shared.type "nfs" }}
          - mountPath: "/mnt/nfs"
            name: nfs-volume
          {{- end }}
          {{- include "trustStoreVolumeMount" . | nindent 10 }}
          {{- include "extraSecretVolumeMount" . | nindent 10 }}
          {{- include "tempVolumeMount" . | nindent 10 }}
        env:
          {{- include "getWaitForEndpointsVar" (dict "dot" . "pod" $podName "endpoints" (printf "%s/version,%s/version" (include "DAS_URL_ROOT_BACKEND" .) (include "ONDEMAND_URL_ROOT_BACKEND" .)) ) | nindent 10 }}
          {{- include "getShutdownEndpointsVar" (dict "dot" . "pod" $podName) | nindent 10 }}
          {{- include "getPodMetadataEnvVars" (dict "values" . "containerName" $containerName) | nindent 10 }}
          {{- include "oauthEnvSecretsCustomNames" (dict "dot" . "idName" "OAUTH2_CLIENT_ID" "secretName" "OAUTH2_CLIENT_SECRET" ) | nindent 10 }}
          {{- include "getVaultEnvVarsInEnvVars" (dict "Values" .Values "Release" .Release) | nindent 10 }}
          {{- include "trustStorePassword" . | nindent 10 }}
          {{- include "extraEnvironmentVars" .Values | nindent 10 }}
          {{- include "getAzureKeyVaultProperties" . | nindent 10 }}
          {{- include "getS3Properties" . | nindent 10 }}
        envFrom: 
        - configMapRef:
            name: {{ .Release.Name }}-upload-included-engine-config
      {{- include "extraContainers" (dict "dot" . "pod" $podName) | nindent 6 }}
      volumes:
{{ if eq .Values.global.storage.shared.type "nfs" }}      
        - name: nfs-volume
{{ if .Values.global.storage.shared.local.enabled }}
          hostPath:
            path: {{required "global.storage.shared.local.path required" .Values.global.storage.shared.local.path}}
{{ else }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-storage-pvc
{{ end }}
{{ end }}
        {{- include "trustStoreVolume" . | nindent 8 }}
        {{- include "extraSecretVolume" . | nindent 8 }}
        {{- include "tempVolume" . | nindent 8 }}
{{- end }}