{{- if include "needOauthSecret" . }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-otds-client-secret
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
stringData:
  oauth2_clientId: {{ required ".Values.global.otds.oauth2.clientId" ((((.Values).global).otds).oauth2).clientId }}
  oauth2_clientSecret: {{ required ".Values.global.otds.oauth2.clientSecret" ((((.Values).global).otds).oauth2).clientSecret }}
{{ if and .Values.global.ot2.enabled ((((.Values.global.ot2).events).callback).oauth2).clientId }}
  ot2_events_callback_clientId: {{ required "global.ot2.events.callback.oauth2.clientId is required" .Values.global.ot2.events.callback.oauth2.clientId }}
  ot2_events_callback_clientSecret: {{ required "global.ot2.events.callback.oauth2.clientSecret is required" .Values.global.ot2.events.callback.oauth2.clientSecret }}
{{- end }}
{{- end }}
