{{- if and .Values.global.tls.enabled (not .Values.global.tls.secretName) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tlsCertName" . }}
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "secret") | nindent 4 }}
type: kubernetes.io/tls
data:
{{- if include "isGcpEnabled" . }}
  tls.crt: {{ required "global.tls.certSecretKey is required" .Values.global.tls.crtSecretKey | b64enc  | indent 4 }}
  tls.key: {{ required "global.tls.keySecretKey is required" .Values.global.tls.keySecretKey | b64enc  | indent 4 }}
{{- else }}
  tls.crt: {{ required "global.tls.crt is required" .Values.global.tls.crt | b64enc  | indent 4 }}
  tls.key: {{ required "global.tls.key is required" .Values.global.tls.key | b64enc  | indent 4 }}
{{- end }}

{{- end }}