{{- if or .Values.global.assuredDelivery.enabled .Values.global.ei.enabled .Values.global.eep.enabled}}
{{- if .Values.global.istio.virtualService.enabled }}
{{- $pathPrefix := include "getFrontEndUrlContextWithTrailingSlash" . }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  {{- include "namespaceMetadata" . | nindent 2 }}
  annotations:
{{ include "getExtraResourceAnnotations" (dict "dot" . "typeLabel" "virtualService") | nindent 4 }}
  labels:
{{ include "getExtraResourceLabels" (dict "dot" . "typeLabel" "virtualService") | nindent 4 }}
spec:
  gateways:
    {{ include "getVirtualServiceGateways" . }}
  hosts:
    - {{ .Values.global.ingress.hostname }}
{{- range $extraHost := .Values.global.istio.virtualService.extraHosts }}
    - {{ $extraHost }}
{{- end }}
    - {{ .Release.Name }}-eep-service
  http:
    - match:
      - uri:
          prefix: /{{ $pathPrefix }}eep
      name: eep-service
      route:
      - destination:
          host: {{ .Release.Name }}-eep-service
          port:
            number: {{ .Values.eep.svc.port }}

{{- end }}
{{- end }}
